# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba4d7ca9b56d0390317d7db45a3d0cc8a202e37d89625d7555fc4dbe2dcff645077931948ef4bb46c7ef050fde90fc1afd76160bd0e470fa8011d097a404cc53

test:
  secret_key_base: a68fa18e12e0aa4878e5354ff999771bf276482c5d77ddff1f5b18d6dbf90d2cac0dc7e2700f46d96b7bdab3333c2f88548715c62809a0c607ec8430cb7e7daa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
